### ISSUE TITLE
debian12.4  Verifying installation        [FAILURE]

### ISSUE THREAD

**Issue by skelgaard** [SoftCreatR/imei#107]
coders/dng.c: In function 'SetLibRawParams':
coders/dng.c:337:13: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  337 |   raw_info->rawparams.max_raw_memory_mb=8192;
      |             ^~~~~~~~~
      |             params
coders/dng.c:340:15: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  340 |     raw_info->rawparams.max_raw_memory_mb=(unsigned int)
      |               ^~~~~~~~~
      |               params
make[1]: *** [Makefile:10714: coders/dng_la-dng.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/local/src/imei/ImageMagick-7.1.1-25'
make: *** [Makefile:6242: all] Error 2
make  install-am
make[1]: Entering directory '/usr/local/src/imei/ImageMagick-7.1.1-25'
  CCLD     MagickCore/libMagickCore-7.Q16HDRI.la
  CC       coders/farbfeld_la-farbfeld.lo
  CC       coders/fax_la-fax.lo
  CC       coders/fits_la-fits.lo
  CC       coders/fl32_la-fl32.lo
  CC       coders/dpx_la-dpx.lo
  CC       coders/ftxt_la-ftxt.lo
  CC       coders/gif_la-gif.lo
  CC       coders/dot_la-dot.lo
  CC       coders/gradient_la-gradient.lo
  CC       coders/gray_la-gray.lo
  CC       coders/hald_la-hald.lo
  CC       coders/hdr_la-hdr.lo
  CC       coders/dng_la-dng.lo
coders/dng.c: In function 'SetLibRawParams':
coders/dng.c:337:13: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  337 |   raw_info->rawparams.max_raw_memory_mb=8192;
      |             ^~~~~~~~~
      |             params
coders/dng.c:340:15: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  340 |     raw_info->rawparams.max_raw_memory_mb=(unsigned int)
      |               ^~~~~~~~~
      |               params
make[1]: *** [Makefile:10714: coders/dng_la-dng.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/local/src/imei/ImageMagick-7.1.1-25'
make: *** [Makefile:12790: install] Error 2

**Comment by eliliam** [comment]
I am having the same error on Debian 12

**Comment by LaikaSa** [comment]
Same issue on my newly WSL Ubuntu 22.04 install

**Comment by SoftCreatR** [comment]
See https://github.com/ImageMagick/ImageMagick/issues/6969

**Comment by LaikaSa** [comment]
Thanks, it seems version 7.1.1-23 currently works fine until they fix it, weird that the thread you linked do not show up when I paste the error onto google

**Comment by SoftCreatR** [comment]
I discovered it, when I was going to implement manual compilation of libraw.
