### ISSUE TITLE
aom is required but not installed

### ISSUE THREAD

**Issue by hooverweb** [SoftCreatR/imei#109]
![imei](https://github.com/SoftCreatR/imei/assets/2574722/4fbd75b8-2cac-47c9-9836-5617136af19c)

I'm not sure why libheif is being skipped. What is missing that I need to install? I'm running cmake 3.28.3.

**Comment by SoftCreatR** [comment]
Please attach the log file.

**Comment by hooverweb** [comment]
Thanks. Here's the log:
[imei-1707502219.log](https://github.com/SoftCreatR/imei/files/14225094/imei-1707502219.log)

**Comment by hooverweb** [comment]
Apologies, the log file indicated I needed to install a compiler. Installing Yasm fixed it.

**Comment by SoftCreatR** [comment]
Should be done by IMEI 🤔
