### ISSUE TITLE
How to clean up after installation? ImageMagick installation consumes 1.3GB of space

### ISSUE THREAD

**Issue by boryn** [SoftCreatR/imei#116]
I install ImageMagick in the docker container (based on ubuntu:24.04), using the standard "one-step" install

```bash
t=$(mktemp) && \
wget 'https://dist.1-2.dev/imei.sh' -qO "$t" && \
bash "$t" && \
rm "$t"
```

It installs correctly but the container swells from 500MB to a whopping 1.8GB. I just cannot believe it needs 1.3GB for ImageMagick? How to minimize the size to just have the necessary files? What could be removed?

![image](https://github.com/user-attachments/assets/7acab9cf-a821-4633-9bd6-afe71793450f)

**Comment by SoftCreatR** [comment]
Try installing it with checkinstall instead, then take the packages, and install them in a fresh container. By default, IMEI installs a lot of build tools, etc.

**Comment by boryn** [comment]
Hi @SoftCreatR 

Thank you for the valuable tip!

Unfortunately I have no experience with `checkinstall`. Could you just give me a hint where I can find the installed packages? Should I just 'copy-paste' them into a new container?

**Comment by SoftCreatR** [comment]
The packages should be in BUILD_DIR, which defaults to /usr/local
Moving them to the container, and installing them using dpkg, should work, yes.
