### ISSUE TITLE
HEIC to JPG conversion fails with Error while loading plugin: No decoding plugin installed for this compression format 

### ISSUE THREAD

**Issue by mig5** [SoftCreatR/imei#119]
Hi,

I am struggling to convert a HEIC file to JPG using your tool

```
$ magick IMG_5348.HEIC IMG_5348.jpg
magick: Error while loading plugin: No decoding plugin installed for this compression format (11.6003) `IMG_5348.HEIC' @ error/heic.c/IsHEIFSuccess/141
```

Do you have any idea?

I found https://github.com/strukturag/libheif/issues/1250 which suggests to not compile as separate plugins. I tried that but it still didn't help.

I am calling the script like so, on an Ubuntu 20.04 64-bit machine:

```
./imei.sh --skip-jxl --force --libheif-version=1.17.6
```

Attaching log file too
[imei-1724201043.log](https://github.com/user-attachments/files/16684066/imei-1724201043.log)

**Comment by SoftCreatR** [comment]
See https://github.com/SoftCreatR/imei/issues/117
