### ISSUE TITLE
How to uninstall Imagick installed with imei

### ISSUE THREAD

**Issue by DecaTec** [SoftCreatR/imei#121]
Installing Imagick with this tool works like charm, thanks a lot!

I just wonder how to (completely) uninstall a version installed with imei. Just in case you have to revert to the version shipping with Ubuntu 22.04, 24.04, etc.

**Comment by SoftCreatR** [comment]
If you didn't use checkinstall, you could just try manually removing everything.

**Comment by DecaTec** [comment]
Wow, thanks for the quick reply!

The question is what's the "everything" here. Where does imei put the compiled stuff which should be removed manually?

**Comment by SoftCreatR** [comment]
> Wow, thanks for the quick reply!
> 
> The question is what's the "everything" here. Where does imei put the compiled stuff which should be removed manually?

See https://github.com/SoftCreatR/imei?tab=readme-ov-file#options-available

By default, you should find everything in `/usr/src/`

**Comment by DecaTec** [comment]
OK, I've tried the checkinstall method and this works on Ubuntu 22.04 and 24.04. The packages can also be easily uninstalled.

I think this one can be closed.
