### ISSUE TITLE
Add support for JPEG XL

### ISSUE THREAD

**Issue by jackyhallyday** [SoftCreatR/imei#13]
Hello,

JPEG XL (https://gitlab.com/wg1/jpeg-xl) support has just been merged to Chromium and can be enabled with a flag.

ImageMagick mentions JPEG XL support (https://imagemagick.org/script/formats.php) :
JXL	RW	JPEG XL image coding system	Requires the JPEG XL delegate library.

Is there a way to add this library during the install of imei, so it would support JPEG XL, too?

**Comment by SoftCreatR** [comment]
Hi,

I've already checked this out and it's planned to automatically add support for JPEG XL. However, as of now, I'm not 100% sure, what's needed. As soon as I've figured out, which requirements need to be met, I'll implement it.

**Comment by SoftCreatR** [comment]
Done :)

**Comment by jackyhallyday** [comment]
Wow! That's great, thank you!

**Comment by jackyhallyday** [comment]
...unfortunately, it didn't work for me.

At first it seems ok during the installation. It didn't so I --force(d) imei to build everything again:
 Installing dependencies       [OK]
 Building aom                  [OK]
 Building libheif              [OK]
 Building jpegxl               [OK]
 Building ImageMagick          [OK]
 Verifying installation        [OK]
 
convert seemed to work, but it generated "classic" JPG files.

> /usr/local/bin/convert -list format
JXL is not in the list

> /usr/local/bin/convert -version
Version: ImageMagick 7.0.11-6 Q32 x86_64 2021-03-28
(...)
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib

> ls -l /usr/local/lib/ImageMagick-7.0.11/modules-Q32HDRI/coders
jxl.la and jxl.lo are there.

Everything seems fine.

Note: I had already installed JPEG XL from the GitLab sources, and I am already producing JXLs by generating PNGs with ImageMagick, then convert them with cjxl. I mean: it definitely compiles on my server.
And the build process of ImageMagick seems normal.

That might be an ImageMagick bug, maybe? I don't know.

**Comment by SoftCreatR** [comment]
Try again with --jxl-version 0.3.3

**Comment by SoftCreatR** [comment]
See https://gitlab.com/wg1/jpeg-xl/-/issues/207

It seems, that IM is currently not fully compatible with JXL.

**Comment by jackyhallyday** [comment]
Great news! https://twitter.com/JackyHallyday/status/1382434351904854025

**Comment by SoftCreatR** [comment]
Well, i don't understand, why it requires a tweet, to get their attention, but better than nothing, i guess 👍

**Comment by SoftCreatR** [comment]
The issue reported at JPEG XL has been labeled as fixed, but there hasn't been any commit yet. So we'll have to wait for the next release, I guess.

**Comment by SoftCreatR** [comment]
Today, a new commit has been pushed to the JXL repo: https://gitlab.com/wg1/jpeg-xl/-/commit/ab7c5e9b6795134377aa4846ceaae2c5bc504f76

I've rebuilt IM 7.0.11-8 using it, but still no luck.

**Comment by SoftCreatR** [comment]
@jackyhallyday Just FYI: It works now without any changes at my end using libjxl 0.3.7 and IM 7.0.11-13.
