### ISSUE TITLE
When using --build-dir HEIF does not work

### ISSUE THREAD

**Issue by trajano** [SoftCreatR/imei#24]
The reason is it's looking for the libaom.so in $BUILD_DIR build it's being created in `/usr/local` since the aom wasn't configured with a prefix.

**Comment by trajano** [comment]
Oh I just saw the fix for this https://github.com/SoftCreatR/imei/commit/cc09d1100871f8bf2a5bbd7f192e9f78e54a74e7

Testing it now.

**Comment by trajano** [comment]
Tweaked it a little by adding an `ldconfig`

```
FROM openjdk:11-jre as test
COPY --from=imagemagick /work/ /usr/local/
RUN ldconfig
WORKDIR /w
COPY citron.HEIC /w/
RUN find /usr/local -type f -print
RUN magick citron.HEIC citron.jpg
```

Still fails
```
#17 0.391 magick: error while loading shared libraries: liblcms2.so.2: cannot open shared object file: No such file or directory
```

**Comment by trajano** [comment]
Yup I am trying to figure out how to just install all the imagemagick dependencies by apt because I am doing it one at a time.

**Comment by partnerinflight** [comment]
Hmm, I'm getting the same error, but without using --build-dir. aom appears to build fine, but heif won't build, says aom isn't installed.

**Comment by SoftCreatR** [comment]
That option is only relevant for imagemagick itself. You may want to check the logfile, and see, if an error occurred during the build of aom.
