### ISSUE TITLE
imei isn't aware of conflicts during dependency installation and incorrectly displays that dependency installation is complete

### ISSUE THREAD

**Issue by hparadiz** [SoftCreatR/imei#28]
## 🚀 Feature

imei should fail out when there is an apt install failure with a dump of the previous command stdout

Another option is to search for the installed packages from the output of `apt list --installed`

## Have you spent some time to check if this issue has been raised before?
Yes

### Have you read the [Code of Conduct](https://github.com/SoftCreatR/imei/blob/main/CODE_OF_CONDUCT.md)?

[x] I have read the Code of Conduct

## Pitch

imei isn't aware of conflicts during dependency installation and incorrectly displays that dependency installation is complete

The result compile ends up not supporting many image types.

It would be useful to have imei either warn you or prompt you with "Looks like some dependencies are still missing. Would you like to continue with compile?"

## Screenshots
![image](https://user-images.githubusercontent.com/195216/121289217-4b528380-c880-11eb-97df-c00896f7d2ea.png)

What actually happens under the hood.

![image](https://user-images.githubusercontent.com/195216/121289255-5c02f980-c880-11eb-885a-339cdf331fb9.png)

**Comment by SoftCreatR** [comment]
There is actually some kind of a check included and it was planned to let the step "Installing dependencies" fail, if anything goes wrong. Obviously, that doesn't work as expected. I'll try to find a solution.

Btw, it would be helpful, if you could attach the file `/var/log/imei.log`.

**Comment by hparadiz** [comment]
Certainly, 

https://paste.ubuntu.com/p/Dvh2wBgryX/

**Comment by SoftCreatR** [comment]
Well, according to the log, there was no problem during the installation of dependencies and even the Delegate library configuration (in the log) differs from the output of `identify -version`.

Could you please try executing `/usr/local/bin/identify -version` instead? Because the only thing that comes in my mind is, that IM is installed twice on the system.

**Comment by hparadiz** [comment]
It compiled fine both times. But the first time it didn't have access to most delegates (see first screenshot in my original post).

Now it shows this:
![image](https://user-images.githubusercontent.com/195216/121310619-40f3b200-c89f-11eb-87c1-948dd4e51ac6.png)

The second time it simply overwrote the first one. It's completely fine now.

**Comment by SoftCreatR** [comment]
So the log file isn't from the failed installation? In this case, I can't really reproduce, what exactly happened.

**Comment by hparadiz** [comment]
Just to be clear. It never failed to install or compile. It simply compiled without all the dependencies it needed. The real issue is that imei skips installing dependencies if apt says there was a conflict during dependency installation.

**Comment by SoftCreatR** [comment]
I understood that. But I can't reproduce this with the logs provided. There is a check included in IMEI that should prevent this kind of failure.
