### ISSUE TITLE
   libheif     [FAILURE]] on update? 

### ISSUE THREAD

**Issue by Rar9** [SoftCreatR/imei#31]
Im trying to update imagemagick to last version but get this error

Version: ImageMagick 7.0.11-14 Q32 x86_64 2021-05-17 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zip zlib
root@mail:~# bash <(curl -sL dist.1-2.dev/imei) --no-sig-verify --imagemagick-version 7.1.0-2 --force           
 ###########################################
 Welcome to IMEI - ImageMagick Easy Install 
 ###########################################

 Detected OS     : Ubuntu 18.04.5 LTS
 Detected Arch   : x86_64
 Detected Cores  : 12

 Used web client : curl

 Work Dir        : /usr/local/src/imei
 Build Dir       : /usr/local
 Log File        : /var/log/imei.log

 Force Build     : yes
 CI Build        : no
 Signature Check : disabled

 #####################
 Installation Process
 #####################

 Installing dependencies       [OK]
 Building aom                  [OK]
 Building libheif              [FAILURE]

 Please check /var/log/imei.log for details.

....
heif-test.go:39:2: no required module provides package github.com/strukturag/libheif/go/heif: go.mod file not found in current directory or any parent directory; see 'go help modules'
Makefile:1161: recipe for target 'heif-test-go' failed
make[2]: *** [heif-test-go] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/heif_convert-encoder.Tpo .deps/heif_convert-encoder.Po
mv -f .deps/heif_convert-encoder_y4m.Tpo .deps/heif_convert-encoder_y4m.Po
mv -f .deps/heif_thumbnailer-encoder.Tpo .deps/heif_thumbnailer-encoder.Po
mv -f .deps/heif_convert-encoder_png.Tpo .deps/heif_convert-encoder_png.Po
mv -f .deps/heif_thumbnailer-encoder_png.Tpo .deps/heif_thumbnailer-encoder_png.Po
mv -f .deps/heif_convert-encoder_jpeg.Tpo .deps/heif_convert-encoder_jpeg.Po
mv -f .deps/heif_thumbnailer-heif_thumbnailer.Tpo .deps/heif_thumbnailer-heif_thumbnailer.Po
mv -f .deps/heif_info-heif_info.Tpo .deps/heif_info-heif_info.Po
mv -f .deps/heif_convert-heif_convert.Tpo .deps/heif_convert-heif_convert.Po
mv -f .deps/heif_test-heif_test.Tpo .deps/heif_test-heif_test.Po
mv -f .deps/heif_enc-heif_enc.Tpo .deps/heif_enc-heif_enc.Po
make[2]: Leaving directory '/usr/local/src/imei/libheif-1.12.0/examples'
Makefile:536: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/imei/libheif-1.12.0'
Makefile:445: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Rar9** [comment]
Found the issue 
My server had snap go version 1.65 installed
Once removed your script worked.

**Comment by SoftCreatR** [comment]
@Rar9 Just FYI: To update to the latest version of IM (or any component), you can omit the `--imagemagick-version` and `--force` flags. This will make sure, that you really get the latest version available, while not re-compiling anything that is already compiled in the latest version :)
