### ISSUE TITLE
[FR] set the CONFIGURE_PATH when building

### ISSUE THREAD

**Issue by mmattel** [SoftCreatR/imei#32]
@SoftCreatR is it possible to define the `CONFIGURE_PATH` in the build process as parameter?

`convert -list configure | grep "ImageMagick-6"`

Default with the U18.04/20.04, this is `/etc/ImageMagick-6/`
But when running a build with your script, you get `/usr/local/etc/ImageMagick-7/`

It would be great if this could be defined

**Comment by SoftCreatR** [comment]
--build-dir should do the trick.

**Comment by mmattel** [comment]
hmmm,
`--prefix="$BUILD_DIR"`

from https://imagemagick.org/script/resources.php
`$PREFIX/etc/ImageMagick-7`
`The environmental variable $PREFIX is the default install path (e.g. /usr/local)`
It does not read to me as configuration path though... (install <> configuration)

Just to be sure before I ruin everything...
If if set `--build-dir=""` it should put the binaries as before, but the config dir is then set to `/etc/ImageMagick-7` right?

**Comment by SoftCreatR** [comment]
Just wondering: Is there a specific reason, why you want to have it installed elsewhere?

**Comment by mmattel** [comment]
Misunderstanding, it is not about _installing_ it at a different location but setting the _config_ directory. At Ubuntu with version 6, the config directory is /etc/ImageMagic-6,means the base directory is / and not /usr/local.

**Comment by SoftCreatR** [comment]
I don't think, that you can set the configuration directory exclusively. It depends on the install path (which is `/usr/local` by default). Setting it to `/` would install the configuration in `/etc`, but install the binaries in `/bin`.

**Comment by mmattel** [comment]
I think I found the solution, you may need to add a additional option with a default. Looking into the configure script and with the help of an answered question in the ImageMagic repo, here are my findings:

`the configure scripts suggest the configure option "--sysconfdir=DIR"`

Taking a look to the ImageMagic configure file:

**at line 4751**
eval "eval SYSCONF_DIR=$sysconfdir"

**at line 33127**
CONFIGURE_PATH="${SYSCONF_DIR}/${CONFIGURE_RELATIVE_PATH}/"

Which is exactly the path of the configuration files ImageMagic is looking at when you use it, see my comments above. Again, it is not about a different installation, but a defined configuration location.

The default option when not defined should be _empty_ and the option must therefore always be handed over to the configure script, which then defaults to filesystem root and creates /etc/ImageMagic-7. Without setting the option and hand it over to the configure script, it will be set to $BUILD_DIR which creates /usr/local/etc/ImageMagick-7/

**Comment by mmattel** [comment]
(Pls note, that I have made some text changes in the comment above to reflect my test below.)

I gave the thing a try to see if it fixes the issue. For this I changed your imei.sh script to:
```
          cd "ImageMagick-$IMAGEMAGICK_VER" &&
          ./configure \
            --prefix="$BUILD_DIR" \
            --sysconfdir="/etc" \
```
and run `sudo ./imei.sh --no-sig-verify --force`

Here is the result running:
`magick identify -list configure | grep CONFIGURE_PATH`

before: `CONFIGURE_PATH        /usr/local/etc/ImageMagick-7/`
after: `CONFIGURE_PATH        /etc/ImageMagick-7/` :white_check_mark: 

The ImageMagick-7 folder with the default config files has been created as expected :white_check_mark: 

`whereis magick`
before: `/usr/local/bin/magick` :white_check_mark: 
after: `/usr/local/bin/magick` :white_check_mark: 

Hopefully this convinces you to add this additional script parameter which defaults to /etc 😄

**Comment by mmattel** [comment]
Great 👍
Thanks a lot!
