### ISSUE TITLE
[FR] add some options

### ISSUE THREAD

**Issue by mmattel** [SoftCreatR/imei#33]
@SoftCreatR 
seen during my tests, I missed some options when calling the script:

* `--remove` to completely remove the installation
ImageMagick and dependencies (like aom ect)
* `--force-imagick`, an option which checks if the dependencies are up to date and (re)builds them if needed, but mandatory forces to rebuild imagick. This is very handy if you eg just change a config option which needs an imagick rebuild while the already build dependencies are up to date. This would shorten build times with changed parametrisation a lot.

Renaming `public.pem` to `imei.public.pem` making it clear whom it belongs to...

**Comment by SoftCreatR** [comment]
> --force-imagick, an option which checks if the dependencies are up to date and (re)builds them if needed, but mandatory forces to rebuild imagick. This is very handy if you eg just change a config option which needs an imagick rebuild while the already build dependencies are up to date. This would shorten build times with changed parametrisation a lot.

While this could be achieved already by using the available lock flags, I've just added the force flag for IM, too.

**Comment by mmattel** [comment]
Could it be that there is a typo?
`echo " Force Build ALl : ${FORCE:-"no"}"` --> `echo " Force Build ALL : ${FORCE:-"no"}"`

**Comment by SoftCreatR** [comment]
It is. However, this may be fixed in the next release :P

**Comment by SoftCreatR** [comment]
IMEI now uses [Checkinstall](https://en.wikipedia.org/wiki/CheckInstall), thus every package can be uninstalled via `apt` or `dpkg`.

As of now, 4 packages are being generated upon install:

- imei-libaom
- imei-libheif
- imei-libjxl
- imei-imagemagick

The generated DEB files are saved at `/usr/local/src`.

In a later release of IMEI, an uninstall command may be added.

**Comment by mmattel** [comment]
Great news, you may want to add a brief description about this news in README so it won´t get lost.
