### ISSUE TITLE
how to set imagemagick-version Q16 

### ISSUE THREAD

**Issue by motz17** [SoftCreatR/imei#36]
First: thumbs up for this great project!!
When downloading imagemagick binaries, the user has the choice of Q8, Q16 and Q32 versions.
I set --imagemagick-version 7.0.8-25 Q16 to the call (so:   `bash <(wget -qO - https://dist.1-2.dev/imei.sh) --no-sig-verify --im-version 7.0.8-25 Q16` )

but I got `Building ImageMagick (Q8)`

other attributes
 Detected OS     : Ubuntu 20.04.2 LTS
 Detected Arch   : x86_64
 Detected Cores  : 7

how can I set to use the Q16 version?

**Comment by SoftCreatR** [comment]
`bash <(wget -qO - https://dist.1-2.dev/imei.sh) --no-sig-verify --im-version 7.0.8-25 --im-q 16`

That should do it.
