### ISSUE TITLE
Two different versions

### ISSUE THREAD

**Issue by esginmurat** [SoftCreatR/imei#4]
Hello. Dear admin; @SoftCreatR thanks for imei.

Ubuntu 20.04 installed on my vps server. I also installed the imagick program with apt. (8: 6.9.10.23 + dfsg-2.1ubuntu11.1)
then I installed imei. installation was smooth. but he still sees the old imagick program on the site.

![imei](https://user-images.githubusercontent.com/17769013/100539222-08b34d00-3246-11eb-91d1-f7fe240412b0.jpg)
![magick](https://user-images.githubusercontent.com/17769013/100539224-0a7d1080-3246-11eb-97b3-6d3f4faeb00e.png)

I will be glad if you help have a nice day.

**Comment by SoftCreatR** [comment]
Though it's not mentioned anywhere, it's advised to uninstall any previously installed ImageMagick version first to avoid such issues.

As soon as you made sure, that there's only one Imagemagick version installed (preferably the one that has been installed using IMEI), you may also compile the Imagick PHP module from source, e.g.:

```bash
apt install php-dev
cd /usr/local/src
git clone https://github.com/Imagick/imagick.git
cd imagick
phpize
./configure
make
make install
```

**Comment by esginmurat** [comment]
Thank you. 👍 
Regards, Greetings from Turkey.
