### ISSUE TITLE
How to install Specific version of ImageMagick?

### ISSUE THREAD

**Issue by vihatsoft** [SoftCreatR/imei#43]
hi,
 i have already install ImageMagick 7.1 
when i run bellow code it will install 7.1. but i want to install ImageMagick 6.9.10. so how can i install ImageMagick 6.9.10?
`t=$(mktemp) && \
wget 'https://dist.1-2.dev/imei.sh' -qO "$t" && \
bash "$t" && \
rm "$t"
`

thank you

**Comment by SoftCreatR** [comment]
Hi,

simply execute imei.sh with `--imagemagick-version 6.9.10-97` 

However, is there a specific reason for 6.9.10 (where the latest version has been released in Feb 2020, while the latest version is 6.9.12). If not, the OS maintainers version may fit your needs.

**Comment by vihatsoft** [comment]
where can i place `--imagemagick-version 6.9.10-97` in bellow code?

`git clone https://github.com/SoftCreatR/imei && \
cd imei && \
chmod +x imei.sh && \
./imei.sh
`

**Comment by SoftCreatR** [comment]
after `"$t"`

**Comment by vihatsoft** [comment]
get error:
 Verifying installation        [FAILURE]

**Comment by SoftCreatR** [comment]
Did you remove any previous installation?

However, please execute identify -version and see, if the installation was successful anyways. Maybe, there's a bug in the verification process.
