### ISSUE TITLE
Any way to compile without HDRI support

### ISSUE THREAD

**Issue by Petah** [SoftCreatR/imei#44]
Hi,

Is there anyway to compile without HDRI support? The docs say to pass `--disable-hdri` to configure, is there a way to forward that through IMEI? https://imagemagick.org/script/high-dynamic-range.php

**Comment by SoftCreatR** [comment]
Unfortunately not. You may replace it yourself: https://github.com/SoftCreatR/imei/blob/main/imei.sh#L776

**Comment by Petah** [comment]
Thanks
