### ISSUE TITLE
Invalid SSL certificate for downloading imei.sh

### ISSUE THREAD

**Issue by SwanX1** [SoftCreatR/imei#48]
Connecting to `https://dist.1-2.dev/imei.sh` provides an invalid SSL certificate, which can only be used for domains `*.softcreatr.com`, `*.softcreatr.de`, `*.softcreatr.dev`, `softcreatr.com`, `softcreatr.de`, `softcreatr.dev`. .dev TLDs have an HSLS security policy which means I can't override the SSL issue. I will use the imei.sh file from this GitHub repository, however be sure to fix this issue.

Certificate SHA-256 fingerprint:
`A9:00:44:FA:0A:FB:59:D7:2A:D5:40:54:F1:7C:F2:9F:9F:44:44:5C:D3:F3:30:10:EB:61:BA:BB:0F:8D:34:51`

**Comment by SoftCreatR** [comment]
Thank you for the info. I knew, I forgot something 🙃
