### ISSUE TITLE
Option to adjust the CFLAGS

### ISSUE THREAD

**Issue by s0ar** [SoftCreatR/imei#66]
Hi,

it would be very useful to have an command line option to adjust the CFLAGS.

Currently, in the imei.sh the setting is the following:

CFLAGS="-O3 -march=native" \
CXXFLAGS="-O3 -march=native" \

If this is used in a container environment, there are problems using this container on other hardware. (Illegal instruction).

It would be great to have an option to fall back to -O0 or an expert option could allow setting the cflags to a desired value.

**Comment by SoftCreatR** [comment]
The latest version provides two new options. However, due to a problem with libheif, GitHub is currently not able to build it :(
