### ISSUE TITLE
Certificate expired on https://dist.1-2.dev/

### ISSUE THREAD

**Issue by noofaq** [SoftCreatR/imei#70]
It seems that SSL certificate has expired on https://dist.1-2.dev/ domain what breaks various scripts. Is it possible to fix that?

**Comment by SoftCreatR** [comment]
Thank you for the information. The certificate has been renewed, and the problem that prevented LE from renewing it should have been fixed.

However, IMEI itself doesn't rely on it, so installing/verifying via git-clone was still working.
