### ISSUE TITLE
Jq error 

### ISSUE THREAD

**Issue by skHollywood** [SoftCreatR/imei#73]
I am getting below error when installing on docker machine.  

> [ 5/11] RUN cd imei && chmod +x imei.sh && ./imei.sh:
#8 0.524 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
#8 1.644 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#8 1.784 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#8 2.491 Get:4 http://deb.debian.org/debian bullseye/main arm64 Packages [8072 kB]
#8 5.714 Get:5 http://deb.debian.org/debian-security bullseye-security/main arm64 Packages [209 kB]
#8 5.835 Get:6 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [12.0 kB]
#8 6.423 Fetched 8501 kB in 6s (1370 kB/s)
#8 6.423 Reading package lists...
#8 8.209 jq: error (at <stdin>:1): Cannot index object with number
#8 8.236 jq: error (at <stdin>:1): Cannot index object with number

**Comment by SoftCreatR** [comment]
Try running imei.sh with `--dev`.

**Comment by skHollywood** [comment]
It worked. thank you
