### ISSUE TITLE
jq: error  again

### ISSUE THREAD

**Issue by skHollywood** [SoftCreatR/imei#74]
Last time I tried with --dev option, it worked, not working today

 > [ 5/11] RUN cd imei && chmod +x imei.sh && ./imei.sh --dev:
#0 0.594 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
#0 0.775 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#0 0.802 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#0 2.207 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
#0 5.650 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [222 kB]
#0 5.707 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
#0 10.70 Fetched 8628 kB in 10s (841 kB/s)
#0 10.70 Reading package lists...
#0 19.75 jq: error (at <stdin>:1): Cannot index object with number
#0 19.92 jq: error (at <stdin>:1): Cannot index object with number

**Comment by SoftCreatR** [comment]
Yeah... `jq` lately drives me crazy. I'll try to build an alternative, that doesn't rely on it.
