### ISSUE TITLE
libheif 1.16.1 update has broken heic support

### ISSUE THREAD

**Issue by nakedgun** [SoftCreatR/imei#78]
The github actions bot updated the version of libheif yesterday to `1.16.1` [in this commit](https://github.com/SoftCreatR/imei/commit/78d23c6cb13db7e7155e2fccb3912f68f3daef1f). This has broken heic support, because version `1.16.1` of [libheif](https://github.com/strukturag/libheif) now uses "CMake instead of autotools", as per the [libheif docs](https://github.com/strukturag/libheif).

If you run **imei.sh**, it'll say libheif installed correctly, but if you check `/var/log/imei.log` you'll see it failed with an error that  "autogen.sh" cannot be found.

Replacing this bit of code here:

```
tar -xf "libheif-$LIBHEIF_VER.tar.gz" &&
  cd "libheif-$LIBHEIF_VER" &&
  ./autogen.sh &&
  ./configure &&
  make
```

with

```
tar -xf "libheif-$LIBHEIF_VER.tar.gz" &&
  cd "libheif-$LIBHEIF_VER" &&
  mkdir build &&
  cd build &&
  cmake --preset=release ..
  make
```

Seems to fix it. However, the log does show some warnings, such as:

```
  WARNING: MISSING PACKAGE

  We could not find development headers for DAV1D.  Do you have the necessary
  dev package installed? This package is NOT REQUIRED and you may ignore this
  warning but by doing so you may miss some functionality of libheif.

  Relevant CMake configuration variables:

    DAV1D_INCLUDE_DIR=<not found>
    DAV1D_LIBRARY=<not found>
```

I'm not familiar with libheif itself & haven't done any further testing - just sharing my findings so far. 

**Note:** The fix above is not safe to merge as is because it will break cases where people supply a custom version of libheif using `--libheif-version`. If libheif <= 1.15.2, it should use the old build command. Anything higher should use CMake.

**Comment by SoftCreatR** [comment]
Thank you for bringing this to my attention. I'll work on a fix as soon as possible.
