### ISSUE TITLE
Missing Sources

### ISSUE THREAD

**Issue by xErik** [SoftCreatR/imei#8]
## 🐛 Bug Report

Installation via IMEI results in a logged error. 
And no delegates (jpg etc.) get installed.

Yet, the installation goes through without aborting or displaying the error:

`E: You must put some ‘source’ URIs in your sources.list`

## Have you spent some time to check if this issue has been raised before?

Solution is to add sources manually in:

`/etc/apt/sources.list`

deb-src http://deb.debian.org/debian buster main
deb-src http://deb.debian.org/debian buster-updates main
deb-src http://security.debian.org/debian-security/ buster/updates main
deb-src http://ftp.debian.org/debian buster-backports main

## Expected behavior

No error logged and and installation of all delegates (jpg etc.)

## Actual Behavior

Error logged but installation not aborted.
Missing delegates (jpg etc.)

## Your Environment

WIN10: Installed Debian WSL from Windows store.

**Comment by SoftCreatR** [comment]
Thank you for your report. This problem is somewhat strange, because the source URLs should exist in the sources list by default. However, this should be easy to fix by temporarily adding a custom sources list for the Installation process.

**Comment by SoftCreatR** [comment]
I've just tried installing on a fresh WSL machine with Debian 10 from the Windows Store and everything worked, as expected.
