### ISSUE TITLE
"Installs" image broken in README

### ISSUE THREAD

**Issue by zooool** [SoftCreatR/imei#82]
And has been for a while now.
![image](https://github.com/SoftCreatR/imei/assets/133055253/90872f18-5fa8-468e-a2d0-c37dacac191e)

**Comment by SoftCreatR** [comment]
The problem is, that countapi doesn't respond anymore :S I will try to find an alternative.

**Comment by zooool** [comment]
> The problem is, that countapi doesn't respond anymore :S I will try to find an alternative.

Well at least there's an image now, even though the technical aspect is still broken. A slight improvement!
