### ISSUE TITLE
Minimum dependant packages if possible

### ISSUE THREAD

**Issue by suntong** [SoftCreatR/imei#88]
_Originally posted by @suntong in https://github.com/SoftCreatR/imei/discussions/87_

If I use the `checkinstall` methods to enable the creation of packages that can be uninstalled at a later time, and copy the built packages to another machine and do installation there, it seems to me that it is requesting more packages than necessary, like `autoconf automake autotools-dev yasm cmake pkg-config` etc...

Hope we can seperate the _runtime_ dependant packages from build-time some day.

**Comment by suntong** [comment]
BTW, found that `libraqm0` was missing from the whole installation, and solved by installing `libraqm0:amd64`. Just FTA.

**Comment by SoftCreatR** [comment]
On which OS?

**Comment by suntong** [comment]
I built with the checkinstall methods under Ubuntu 22.04.2 LTS, and install the built packages to another (Debian 12) machine --

Debian GNU/Linux 12 (bookworm)

**Comment by SoftCreatR** [comment]
And on which OS is libraqm0 missing? IMEI has built-in exceptions for Debian Stretch and Ubuntu Xenial.

**Comment by suntong** [comment]
Debian 12

**Comment by SoftCreatR** [comment]
I can't reproduce this. On a fresh debian 12 installation, libraqm0 exists.

**Comment by suntong** [comment]
> On a fresh debian 12 installation, libraqm0 exists.

You meant you have libraqm0 right out of the box right? I do minimum installation for both of my Ubuntu and Debian. IE my Debian (and Ubuntu) doesn't have it by default.

**Comment by SoftCreatR** [comment]
Please see, if version 6.9.0 fixed this issue.

**Comment by suntong** [comment]
Thanks, I've giving it a try now...

**Comment by SoftCreatR** [comment]
There's no cleaning of the scroll back log. 

What happens, if you paste `echo -ne "\ec"` in your console? Does that remove your scroll back log as well?

**Comment by suntong** [comment]
> if you paste `echo -ne "\ec"` in your console? Does that remove your scroll back log as well?

yeah, my scroll back log is gone by doing that.

**Comment by SoftCreatR** [comment]
> > if you paste `echo -ne "\ec"` in your console? Does that remove your scroll back log as well?
> 
> yeah, my scroll back log is gone by doing that.

I can't reproduce this. What about `clear -x`?

**Comment by suntong** [comment]
> I can't reproduce this. 

What terminal are you using? Have you tried it with xterm?

> What about clear -x?

That'll keep most of my scroll back log, just the last screenful of logs is gone.

**Comment by suntong** [comment]
Rest of the feedbacks:

- I started with `sudo rm /usr/local/src/imei-*`, then ran the script with `bash "$t" --use-checkinstall`, however, this is what I got:

```sh
. . .
 #####################
 Installation Process
 #####################

 Installing dependencies       [OK]
 Building aom                  [SKIPPED]
 Building libheif              [SKIPPED]
 Building jpegxl               [SKIPPED]
 Building ImageMagick (Q16)    [SKIPPED]
 Verifying installation        [OK]
 Process has been finished successfully after 22 seconds!

$ dir /usr/local/src/
total 0
```

I.e., when using `--use-checkinstall` better make sure all packages are indeed re-generated (even without re-compiling).

As for the minimum dependant package issue, yes, the problem is fixed. Thanks. I'll leave this issue open for you if you want to close it after making sure all packages are re-generated if they are missing from /usr/local/src/.

PS. 

```
# prove that the minimum dependant package issue is fixed
(logs gone again, will redo & supply after bash "$t" --use-checkinstall --force-imagemagick)
```

**Comment by SoftCreatR** [comment]
> logs gone again

You sure?

https://github.com/SoftCreatR/imei/commit/6c75fb9bc9853c0d1f2ae155eff182f72fe85681#diff-49155aca3829a4bb7ba8eb07d3f0b772dc7dad1fe7e04f0db1d1f8dc9485c0c1R269-R271

As you can see, log files are no longer being removed by IMEI. So for every execution, a new log file is being generated, retaining the previous ones.

**Comment by suntong** [comment]
_"prove that the minimum dependant package issue is fixed"_ updated.
