### ISSUE TITLE
Doesn't compile on Rasbian 10

### ISSUE THREAD

**Issue by IanCassTwo** [SoftCreatR/imei#9]
AOM doesn't compile on Rasbian 10 Buster on a Raspberry Pi 4. I fixed by adding -DCMAKE_C_FLAGS="-mfloat-abi=hard -march=armv7-a -marm -mfpu=neon" to the build flags

**Comment by SoftCreatR** [comment]
Unfortunately, I don't have a Pi here for testing. I'll try to fix it blindly.

**Comment by SoftCreatR** [comment]
A possible fix has been implemented via bcd2e075050e963fd8f370aafde8c85f375e2096
