### ISSUE TITLE
Installing dependencies list based on cli choices

### ISSUE THREAD

**Issue by suntong** [SoftCreatR/imei#93]
When installing dependencies, and the cli has opted out of building aom and/or jpeg-xl, those dependencies especially installed for them should be skipped. 

I.e., the dependent list should be build up step by step, as per what delegates will need to be built-in.

**Comment by SoftCreatR** [comment]
While I understand the idea, it makes things pretty complicated.

**Comment by suntong** [comment]
ok, but the logic is already _almost_ there:

https://github.com/SoftCreatR/imei/blob/7cd7071d5f7e6ab73e8270ce716c24d5c1c18478/imei.sh#L941-L961

just need to build up build dependencies for each case.

**Comment by SoftCreatR** [comment]
No, that won't work like this. Splitting the BUILD dependencies is way more complicated, and has little benefit, because most people will install IM including full delegate support.

**Comment by suntong** [comment]
Ok, sure.
