### ISSUE TITLE
delegate failed `'dwebp'

### ISSUE THREAD

**Issue by suntong** [SoftCreatR/imei#95]
Symptom:

```sh
$ identify /tmp/test.webp 
identify: delegate failed `'dwebp' -pam '%i' -o '%o'' @ error/delegate.c/InvokeDelegate/1924.
identify: unable to load module '/usr/local/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/webp.la': file not found @ error/module.c/OpenModule/1291.
identify: unable to open file '/tmp/magick-KaC5RluS7eQOHIwYj93unSHJd5AmyKSJ': No such file or directory @ error/constitute.c/ReadImage/785.
```

But I've already have all these packages installed:

```
ii libwebp-dev:amd64  amd64 Lossy compression of digital photographic images
ii libwebp7:amd64  amd64 Lossy compression of digital photographic images
ii libwebpdemux2:amd64  amd64 Lossy compression of digital photographic images.
ii libwebpmux3:amd64  amd64 Lossy compression of digital photographic images
```

Symptom the same on both Debian GNU/Linux 12 (bookworm) and Ubuntu 22.04.2 LTS.

**Comment by SoftCreatR** [comment]
Can't reproduce this:

![image](https://github.com/SoftCreatR/imei/assets/81188/ed75eb5c-4438-476c-8e88-1cf712db373e)

**Comment by suntong** [comment]
OK, I built on Ubuntu 20.04, which might be the cause.

**Comment by suntong** [comment]
Hmm.. instead of running `identify` in the _build_ environment, which will have the full dependencies, better test the built package in an _empty_ Ubuntu.

**Comment by SoftCreatR** [comment]
That's what I did.

**Comment by SoftCreatR** [comment]
Or are you still working with checkinstall?

**Comment by suntong** [comment]
Yes, using the latest `--use-checkinstall` and `--build-only`

**Comment by SoftCreatR** [comment]
Fine. Give me 10 minutes to test that as well.

**Comment by suntong** [comment]
> That's what I did.

Your're running `identify` in the _build_ environment, which will have the full dependencies before build, right?

**Comment by SoftCreatR** [comment]
> > That's what I did.
> 
> Your're running `identify` in the _build_ environment, which will have the full dependencies before build, right?

I always create a fresh server, and run a default installation.

**Comment by suntong** [comment]
```
 #####################
 Installation Process
 #####################

 Installing dependencies       [OK]
```

This is the step I was talking about -- before build was even started, a full _**build**_ dependencies is installed on to the system. 

Yet, when the built package is installed into an empty Ubuntu, that might be the real cause of this issue.

**Comment by SoftCreatR** [comment]
I already understood, what you were talking about, and I can reproduce this issue actually.

**Comment by SoftCreatR** [comment]
Found the problem. I'm currently perfoming a final test, before publishing version 6.10.1, that should fix it.

**Comment by suntong** [comment]
hmm... when would https://dist.1-2.dev/imei.sh be updated? 

I just did a rebuild from it but found the built version is still 6.10.0.

**Comment by SoftCreatR** [comment]
As soon as I draft a new release on GitHub, which happened just now.
