### ISSUE TITLE
Illegal instruction in Docker 

### ISSUE THREAD

**Issue by SoftCreatR** [SoftCreatR/imei#96]
Is the imei6.10 working for you?

```sh
$ identify --version
Version: ImageMagick 7.1.1-15 Q16-HDRI x86_64 98eceff6a:20230729 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (11.4)

$ identify /usr/share/yelp/icons/hicolor/16x16/status/yelp-page-ui.png
Illegal instruction (core dumped)
```

- I've build (with docker) twice, and twice I'm getting the above. 
- I then _revert_ to v7.1.1-15-imei**6.9.0** and it works _fine_, 
- I then _reinstall_ v7.1.1-15-imei**6.10.1** and it core dumped _again_.

Tested under Ubuntu 22.04.2 LTS.

If you want, I can post the links to my built packages so that you can take a look / try at your side as well.

_Originally posted by @suntong in https://github.com/SoftCreatR/imei/issues/92#issuecomment-1703997596_

**Comment by SoftCreatR** [comment]
Using checkinstall, I guess? Their contents didn't change, so I have no explanation for this behavior. Maybe I can try reproducing this, later this day.

**Comment by suntong** [comment]
thanks for looking into it. the Dockerfile is [here](https://github.com/suntong/ImageMagick-Build/blob/master/Dockerfile). The basic logic is:

```Dockerfile
ARG BASE_IMAGE=ubuntu:20.04
FROM ${BASE_IMAGE}

ARG t=/tmp/imei.sh # $(mktemp)
ARG p="--use-checkinstall --build-only --skip-aom --skip-jpeg-xl"

RUN wget 'https://dist.1-2.dev/imei.sh' -qO "$t"
RUN --mount=type=cache,target=/var/cache/apt bash "$t" $p || true && ls -l /usr/local/src/ || true
```

I wasn't expecting such weird error either, maybe I'll make it multi-stage build 

- build the `.deb` in on layer
- and copy the built `.deb` into another layer
- and to the verification there. 

The built `.deb` files are:

- https://dl.cloudsmith.io/public/suntong/repo/deb/any-distro/pool/any-version/main/i/im/imei-imagemagick_7.1.1-15-imei6.9.0/imei-imagemagick_7.1.1-15-imei6.9.0_amd64.deb
- https://dl.cloudsmith.io/public/suntong/repo/deb/any-distro/pool/any-version/main/i/im/imei-imagemagick_7.1.1-15-imei6.10.1/imei-imagemagick_7.1.1-15-imei6.10.1_amd64.deb

**Comment by suntong** [comment]
> maybe I'll make it multi-stage build

Done, but haven't get a chance to test it yet...

**Comment by suntong** [comment]
The [Dockerfile](https://github.com/suntong/ImageMagick-Build/blob/master/Dockerfile) tested fine by itself 🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️
Yet I installed the built packages to my VPS and it is error with `Illegal instruction (core dumped)` again

The newly built package (tested fine within docker) is at
https://dl.cloudsmith.io/public/suntong/repo/deb/any-distro/pool/any-version/main/i/im/imei-imagemagick_7.1.1-15-imei6.10.1/imei-imagemagick_7.1.1-15-imei6.10.1_amd64.deb

**Comment by suntong** [comment]
BTW,

> I'll make it multi-stage build
> 
> * build the `.deb` in on layer
> * and copy the built `.deb` into another layer
> * and do the installation & verification there.

I found from this way that the `libxml2` is missing from the imei-imagemagick dependencies.

**Comment by suntong** [comment]
> The [Dockerfile](https://github.com/suntong/ImageMagick-Build/blob/master/Dockerfile) tested fine by itself 🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️
> Yet I installed the built packages to my VPS and it is error with `Illegal instruction (core dumped)` again

Building using docker image `ubuntu:20.04`, I found that the built packages cannot be used in other machines, but only to the built machine itself --

- I tried to build with two cloud providers, and none of the the built packages can be used in my VPS.
- I then build in my VPS and the the built packages can be used in my VPS (ubuntu:22.04).
- however, it cannot be used in my Debian. 

This is so strange, and this is the first time that I ever see such behaviour. 

Would you be able to identify where the Illegal instruction come please?

**Comment by SoftCreatR** [comment]
It's mentioned in the readme since Checkinstall support was introduced, that this can be problematic. Especially, because it's been kind of abandoned.

**Comment by suntong** [comment]
OK. I'm on my own. 
I'll see if I can get to the bottom of it. . .

**Comment by suntong** [comment]
I tried to ask the question in the Debian package building community, started with:

> The ImageMagick has stayed in V6 for too long and I tried to compile its V7 myself to see what the problem might be, and indeed I found a big problem -- I got "Illegal instruction" when I tried to install the built package elsewhere. 

and ended with a question:

> With current cloud-compiling approaches, how should we make sure that the built package works for the older x86_64 CPUs possible

I think it is a legitimate question, and the Debian community would generally benefit from an alternative source for the latest ImageMagick package, but I have just forgotten how unhelpful that mlist had been, and this time it is no exception at all. The most vocal person is also the most narrow-minded person who frowns upon all non-traditional ways of package building, and checkinstall especially, so he completely shut me off, and not even allowing other people to help at all. And indeed, I waited for a week and no one helped. 

I was trying to seek a way to build the latest ImageMagick package for the general public, but now I don't care anymore. As long as I can build for myself, I'm happy, who cares the other people. 

This issue can be closed now.

**Comment by Renkas** [comment]
I'm having same issue. But I'm not using checkinstall.
Issue happens only when running my container in AWS ECS ...

I have no idea how to debug this any further so I'm going back to compiling things myself

**Comment by SoftCreatR** [comment]
Could you please try

```bash
imei.sh --build-cflags="-O0" --build-cxxflags="-O0"
```

**Comment by suntong** [comment]
> Could you please try executing imei.sh with . . . 

BRAVO!!! 

It works!!!

> Building using docker image `ubuntu:20.04`, I found that the built packages cannot be used in other machines, but only to the built machine itself --
> 
> * I tried to build with two cloud providers, and none of the the built packages can be used in my VPS.
> * I then build in my VPS and the the built packages can be used in my VPS (ubuntu:22.04).
> * however, it cannot be used in my Debian.

So I repeated above with the new flags, I.e., 

Building using docker image `ubuntu:20.04` in cloud provider, and tried to run the built binary in my VPS, then tried them in my Debian, BOTH case OK!!

```sh
$ identify --version && convert -version && magick -version
Version: ImageMagick 7.1.1-20 Q16-HDRI x86_64 2cfa8d113:20231008 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (9.4)
Version: ImageMagick 7.1.1-20 Q16-HDRI x86_64 2cfa8d113:20231008 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (9.4)
Version: ImageMagick 7.1.1-20 Q16-HDRI x86_64 2cfa8d113:20231008 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (9.4)
```

This issue can be closed. Finally!

Thanks for getting to the bottom of it eventually! Cheers!

**Comment by suntong** [comment]
My (heavily stripped) pre-built binary that have _proven_ to be working under both ubuntu:22.04 and Debian GNU/Linux 12 (bookworm) is available at [imei-imagemagick_7.1.1-20-imei6.10.3_amd64.deb](https://dl.cloudsmith.io/public/suntong/repo/deb/any-distro/pool/any-version/main/i/im/imei-imagemagick_7.1.1-20-imei6.10.3/imei-imagemagick_7.1.1-20-imei6.10.3_amd64.deb) BTW, FTA.

**Comment by SoftCreatR** [comment]
Could you eventually test this as well?

```bash
--build-cflags="-O3 -mtune=generic" --build-cxxflags="-O3 -mtune=generic"
```

**Comment by SoftCreatR** [comment]
Fixed via 73b4e3738ab11f4f5623e34e365bb7a8859afd96

**Comment by suntong** [comment]
OK, so I gave it a try, but there something wrong with the https://dist.1-2.dev/imei.sh script. I've tried several times, and every time I'm getting `Signature verification failed!`

```sh
t=/tmp/imei.sh

wget 'https://dist.1-2.dev/imei.sh' -qO "$t"

$ grep '^# Version *: ' "$t"
# Version        : 6.10.4

$ sudo bash "$t"
 Signature verification failed! (2)

 Please check /var/log/imei-1697582110.log for details.

$ cat /var/log/imei-1697582110.log
Verification Failure
```

Please double check.

**Comment by SoftCreatR** [comment]
That's strange. I'll check that later. Until then, use --dev

**Comment by SoftCreatR** [comment]
> Yeah, downloading directly from
https://raw.githubusercontent.com/SoftCreatR/imei/main/imei.sh gives the same error as well.
> 
> And yes, --dev was able to make me going.

There was a bug in the workflow, that is supposed to automatically create a new release. It used an old signature file, when creating the release. I've (hopefully) fixed that, and rebased everything, so that the new 6.10.4 should be correct.

**Comment by suntong** [comment]
> so that the new 6.10.4 should be correct.

Yes! verified just now.
