### ISSUE TITLE
How to install a specific imagemagick version?

### ISSUE THREAD

**Issue by jackyhallyday** [SoftCreatR/imei#97]
Hello,
I'm trying to install a specific Imagemagick version, but this doesn't seem to work.
With the latest version, I tried :
./imei.sh --no-sig-verify --force-im --im-version=7.1.0-47
But It still compiles ImageMagick 7.1.1-15 in /usr/local/bin/magick
I also downloaded IMEI 6.7.0 and tried the same after a "rm /usr/local/bin/magick", I changed manually the version in /versions before running imei.sh, but everything I try installs ImageMagick 7.1.1-15.
Am I missing something ?
Thanks.

**Comment by SoftCreatR** [comment]
I'll check that tomorrow.

**Comment by SoftCreatR** [comment]
You were supposed to use `--im-version 7.1.0-47` instead of `--im-version=7.1.0-47`. However, version 6.10.2 should support both.
